[package]
name = "g3"
version = "0.1.0"
authors = ["Werner Laurensse <werner@alman.ax>"]
edition = "2021"
resolver = "2"

[features]
bevy = ["bevy_ecs", "glam"]

[dependencies]
core_simd = { git = "https://github.com/rust-lang/stdsimd", package = "core_simd", rev = "cad7434" }
std_float = { git = "https://github.com/rust-lang/stdsimd", package = "std_float", rev = "cad7434" }
glam = { version = "0.20.0", optional = true }
bevy_ecs = { version = "0.6.1", optional = true }

[dev-dependencies]
peg = "0.8.0"
fxhash = "0.2.1"
