[package]
name = "g3"
version = "0.1.0"
authors = ["Werner Laurensse <werner@alman.ax>"]
edition = "2021"
resolver = "2"

[features]
#plot = ["bevy", "bevy_ecs", "glam"]
#mirror = ["bevy", "bevy_core", "bevy_time", "bevy_app", "glam"]
#mirror = ["winit", "glam", "cfg-if", "env_logger", "log", "wgpu", "pollster", "anyhow", "bytemuck", "cgmath", "image", "hecs"]
plot = ["winit","glam","env_logger","rend3","rend3-framework","rend3-routine","pollster","wgpu","bytemuck","itertools","fxhash","image"]

[dependencies]
std_float = { git = "https://github.com/rust-lang/stdsimd", package = "std_float", rev = "cad7434" }

glam = { version = "0.21", optional = true }
winit = { version = "0.26", optional = true }
rend3 = { git = "https://github.com/BVE-Reborn/rend3", rev = "1452918", package = "rend3", optional = true }
rend3-routine = { git = "https://github.com/BVE-Reborn/rend3", rev = "1452918", package = "rend3-routine", optional = true }
rend3-framework = { git = "https://github.com/BVE-Reborn/rend3", rev = "1452918", package = "rend3-framework", optional = true }
env_logger = { version = "0.9", default-features = false, features = ["termcolor", "atty"], optional = true }
pollster = { version = "0.2", optional = true }
wgpu = { version = "0.13.1", optional = true }
bytemuck = { version = "1.5", features = [ "derive" ], optional = true }
itertools = { version = "0.10.3", optional = true }
fxhash = { version = "0.2.1", optional = true }
image = { version = "0.23", default-features = false, features = ["png", "jpeg"], optional = true}
#hecs = "0.8.2"

#[target.'cfg(target_arch = "wasm32")'.dependencies]
#console_log = "0.2"
#console_error_panic_hook = "0.1"
#js-sys = "0.3"
#web-sys = "0.3"
#wasm-bindgen = "=0.2.81"
#wasm-bindgen-futures = "0.4"
#
#[target.'cfg(target_os = "android")'.dependencies]
#ndk-glue = { version = "0.5", features = ["logger"] }
#
#[package.metadata.android]
#build_targets = ["aarch64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version = 28
target_sdk_version = 28
compile_sdk_version = 28

# Enable high optimizations for dependencies but not for our code:
[profile.dev.package."*"]
opt-level = 3

hecs = { version = "0.7.6", optional = true }

#[target.'cfg(target_arch = "wasm32")'.dependencies]
#console_log = "0.2"
#console_error_panic_hook = "0.1"
#js-sys = "0.3"
#web-sys = "0.3"
#wasm-bindgen = "=0.2.78"
#wasm-bindgen-futures = "0.4"

#bevy_core = { version = "0.7.0", optional = true }
#bevy_time = { version = "0.7", optional = true }
#bevy_app = { version = "0.7", optional = true }

#[target.'cfg(target_arch = "wasm32")'.dependencies]
#console_error_panic_hook = "0.1.6"
#console_log = "0.2.0"
#wgpu = { version = "0.12", features = ["webgl"]}
#wasm-bindgen = "0.2.76"
#wasm-bindgen-futures = "0.4.30"
#web-sys = { version = "0.3.53", features = [
#    "Document",
#    "Window",
#    "Element",
#]}

#opt-level = 3

[[example]]
name = "ball"
required-features = ["plot"]

[[example]]
name = "differentiation"
required-features = ["plot"]

[[example]]
name = "icosahedron"
required-features = ["plot"]

[[example]]
name = "planes"
required-features = ["plot"]