[package]
name = "g3"
version = "0.1.0"
authors = ["Werner Laurensse <werner@alman.ax>"]
edition = "2021"
resolver = "2"

[features]
mirror = ["wgpu", "winit", "baryon", "mint", "pollster", "glm", "env_logger", "itertools", "bytemuck"]

[dependencies]
core_simd = { git = "https://github.com/rust-lang/stdsimd" }
baryon = { git = "https://github.com/wrnrlr/baryon", rev = "634ea6d", optional = true }
mint = { version = "0.5.8", optional = true }
pollster = { version = "0.2.4", optional =  true }
glm = { package="nalgebra-glm", version = "0.13.0", optional =  true }
raw-window-handle = { version = "0.3", optional = true }
winit = { version = "0.25", optional = true }
wgpu = { version="0.11", optional = true }
env_logger = { version = "0.8.3", optional = true }
itertools = { version = "0.10.0", optional = true }
bytemuck = { version = "1.5.1", features = ["derive"], optional = true }

[dev-dependencies]
peg = "0.7.0"

[[example]]
name = "elements"
required-features = ["mirror"]
